-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: May 31, 2018 at 04:52 PM
-- Server version: 5.6.38
-- PHP Version: 7.2.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `recipe_database`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes-main`
--

CREATE TABLE `recipes-main` (
  `recipe-id` int(11) NOT NULL,
  `recipe-title` varchar(255) NOT NULL,
  `recipe-sub-title` varchar(255) NOT NULL,
  `recipe-description` text NOT NULL,
  `recipe-thumb` varchar(255) NOT NULL,
  `ingredients-img` varchar(255) NOT NULL,
  `spicy-level` tinyint(1) NOT NULL,
  `difficulty-level` tinyint(1) NOT NULL,
  `time-level` tinyint(1) NOT NULL,
  `img-folder` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `recipes-main`
--

INSERT INTO `recipes-main` (`recipe-id`, `recipe-title`, `recipe-sub-title`, `recipe-description`, `recipe-thumb`, `ingredients-img`, `spicy-level`, `difficulty-level`, `time-level`, `img-folder`) VALUES
(1, 'Ancho-Orange Chicken', 'with Kale Rice & Roasted Carrots', 'Weʼre amping up chicken breasts with a glaze of smoky ancho chile paste and fresh\r\norange juice in this recipe. On the side, roasted carrots and lightly creamy, golden\r\nraisin-studded rice perfectly accent the sweetness of the glaze.', '0101_FPP_Chicken-Rice_97338_WEB_SQ_hi_res', '0101_ING_FPP_large_feature', 2, 1, 3, 'Recipe_Ancho-Orange_Chicken_with_Kale_Rice_Roasted_Carrots'),
(2, 'Beef Medallions & Mushroom\r\nSauce', 'with Mashed Potatoes\r', 'In this easy recipe, inspired by steak Diane (an American restaurant classic), weʼre\r\nsearing beef medallions, then using the fond in the pan to make a rich, bright mushroom\r\nsauce for spooning on top. Garlic mashed potatoes and sautéed kale make for delicious,\r\nsimple sides.', '0101_2PM_Steak-Diane_97315_SQ_hi_res', 'ING_1-1_2PM_large_feature', 1, 1, 1, 'Recipe_Beef_Medallions_Mushroom_Sauce_with_Mashed_Potatoes'),
(3, 'Broccoli & Basil Pesto\r\nSandwiches', 'with Romaine & Citrus Salad', 'These Italian focaccia sandwiches are layered with broccoli, three cheeses, and a\r\nsavory basil, cashew, and pine nut pesto, then baked in the oven to meld all the bright,\r\naromatic flavors. On the side, weʼre serving a refreshing salad of romaine and seasonal\r\nclementine, dressed in a creamy dressing made with fresh clementine juice.', '1225_FPV_Pesto_-Broccoli-Sandwich_74916_WEB_SQ_hi_res', '1225_ING_FPV_large_feature', 1, 3, 3, 'Recipe_Broccoli_Basil_Pesto_Sandwiches_with_Romaine_Citrus_Salad'),
(4, 'Broccoli & Mozzarella Calzones', 'with Caesar Salad', 'These calzones are loaded with melty fresh mozzarella, creamy ricotta, and tender\r\nbroccoli—balanced by a tangy tomato dipping sauce. For a refreshing side, weʼre\r\ntossing crunchy romaine and briny black olives in our take on Caesar dressing.', '0101_FPV_Broccoli-Calzones_97286_WEB_SQ_hi_res', '0101_ING_FPV_large_feature', 1, 2, 2, 'Recipe_Broccoli_Mozzarella_Calzones_with_Caesar_Salad'),
(5, 'Bucatini Alfredo\r', 'with Broccoli', 'This quick-cooking recipe captures all the deliciously creamy, rich flavor of the classic\r\nItalian-American sauce—with the welcome addition of quick-braised broccoli. A dusting\r\nof pecorino cheese completes each bowl with a touch of sharpness.', '0101_2PV1_Broccoli-Bucatini-Fettuccine_97230_SQ_hi_res', 'ING_1-1_2PV1_large_feature', 2, 2, 2, 'Recipe_Bucatini_Alfredo_with_Broccoli'),
(6, 'Bucatini & Tomato Sauce\r', 'with Roasted Broccoli\r', 'Made with petite datterini tomatoes, the sauce for tonightʼs bucatini highlights briny\r\nolives and capers, hot red pepper flakes, and savory Grana Padano cheese. Weʼre\r\nmixing in roasted broccoli for contrasting texture and nutty-sweet flavor.', '1225_2PV1_Bucatini_100082_SQ_hi_res', 'ING_12-25_2PV1_large_feature', 2, 2, 3, 'Recipe_Bucatini_Tomato_Sauce_with_Roasted_Broccoli'),
(7, 'Cheesy Enchiladas Rojas', 'with Mushrooms & Kale', 'Our hearty vegetarian enchiladas are filled with a combination of fragrant, Mexicanspiced\r\nrice and sautéed mushrooms and kale. For even more flavor, weʼre baking them\r\nunder a smoky-sweet tomato sauce flavored with ancho chile paste and a layer of melty\r\nwhite cheddar. A dollop of lime-seasoned sour cream adds creamy, cooling balance.\r\n(You may receive green curly, dark green lacinato, or red kale.)', '1120_FPV_Emchiladas_74891_WEB_SQ_hi_res', '1218_ING_FPV_large_feature', 1, 3, 1, 'Recipe_Cheesy_Enchiladas_Rojas_with_Mushrooms_Kale'),
(8, 'Crispy Fish Sandwiches\r', 'with Tartar Sauce & Roasted Sweet Potato Wedges', 'These sandwiches highlight wild Alaskan pollock—flavored with aromatic seasonings,\r\ncoated with panko breadcrumbs, and pan-fried for a golden-brown crust. In classic\r\nfashion, a tangy, mayo-based tartar sauce perfectly balances the fish.', '0101_FPF_Crispy-Wild-Alaskan-Pollock_97377_WEB_SQ_hi_res', '0101_ING_FPF_large_feature', 1, 1, 3, 'Recipe_Crispy_Fish_Sandwiches_with_Tartar_Sauce_Roasted_Sweet_Potato_Wedges'),
(9, 'General Tso\'s Chicken', 'with Bok Choy & Jasmine Rice', 'In this quick-cooking spin on a takeout favorite, hoisin sauce, honey, sriracha, and\r\nsesame oil lend our chicken the sweet, spicy, and nutty flavors General Tsoʼs is known\r\nfor. A light dusting of cornstarch on the chicken just before it hits the pan creates a\r\ndelicately crispy exterior (and helps it soak up the irresistible sauce later).', '0101_2PRE07_General-Tsos-Chicken_97217_WEB_SQ_hi_res', '0101_ING_2PRE07_large_feature', 3, 2, 2, 'Recipe_General_Tsos_Chicken_with_Bok_Choy_Jasmine_Rice'),
(10, 'Hoisin-Glazed Pork Chops', 'with Stir-Fried Vegetables & Wonton Noodles', 'Delightfully chewy wonton noodles tossed in a nutty, savory sauce are a delicious\r\naccompaniment to these pork chops. For depth of flavor, weʼre pan-searing the pork\r\nchops, then glazing them with barbecue-like hoisin, whose sweetness perfectly\r\nmatches bites of sautéed carrots in the noodles.', '0101_FPM_Pork-Chops_97303_WEB_SQ_hi_res', '0101_ING_FPM_large_feature', 2, 2, 3, 'Recipe_HoisinGlazed_Pork_Chops_with_StirFried_Vegetables_Wonton_Noodles'),
(11, 'Honey-Butter Barramundi', 'with Za\'atar Roasted Vegetables', 'This Middle Eastern recipe pairs crispy barramundi—served in a family-friendly pan\r\nsauce of honey and butter—with a medley of winter vegetables. For savory, herby flavor,\r\nweʼre seasoning the vegetables with zaʼatar before roasting them.', '0108_FPF_Barramundi_0304_WEB_SQ_hi_res', '0108_ING_FPF_AR_large_feature', 1, 2, 3, 'Recipe_HoneyButter_Barramundi_with_Zaatar_Roasted_Vegetables'),
(12, 'Kale & Ricotta Quiche', 'with Romaine, Apple, & Almond Salad', 'This crowd-pleasing quiche showcases a rich, eggy filling made with ricotta and cream\r\n—balanced by hearty sautéed kale. On the side, weʼre serving a refreshing salad of\r\ncrisp romaine and apple, wrapped in a creamy lemon dressing.', '0108_FPV_Kale-Quiche_97823_WEB_SQ_hi_res', '0108_ING_FPV_large_feature', 2, 2, 2, 'Recipe_Kale_Ricotta_Quiche_with_Romaine_Apple_Almond_Salad'),
(13, 'Mexican-Spiced Barramundi', 'with Kale, Sweet Potato, & Avocado Salad', 'Zesty spiced barramundi is the perfect partner for a salad of roasted sweet potato and kale,\nmarinated in a creamy avocado and citrus dressing to soften the leaves.', '0108_2PF_Barramundi_98380_SQ_hi_res', 'ING_1-8_2PF_large_feature', 1, 1, 2, 'Recipe_MexicanSpiced_Barramundi_with_Kale_Sweet_Potato_Avocado_Salad'),
(14, 'Mushroom & Potato Tacos', 'with Romaine & Orange Salad', 'For this hearty vegetarian meal, weʼre filling soft flour tortillas with mushrooms and\r\npotato—seasoned with a zesty, chorizo-inspired blend, then roasted. A pickled pepper\r\nrelish lends bright flavor to the tacos, all tied together with a creamy sauce seasoned\r\nwith the same spices. Our side salad of juicy orange and crunchy romaine rounds out\r\nthe dish.', '0108_2PF_Barramundi_98380_SQ_hi_res', 'ING_1-8_2PF_large_feature', 2, 2, 3, 'Recipe_Mushroom_Potato_Tacos_with_Romaine_Orange_Salad'),
(15, 'Parmesan-Crusted Chicken\r', 'with Mashed Sweet Potatoes & Roasted Broccoli', 'In this simple, seasonal recipe, youʼll coat chicken in a combination of flour, parmesan\r\ncheese, and savory spices before pan-searing it. Weʼre adding more of the same spices\r\nto a bright, creamy sauce, perfect for spooning over the chicken and broccoli.', '0108_FPP_Baked-Parmesan-Chicken_98333_WEB_Center_hi_res', '0108_ING_FPP_large_feature', 1, 2, 2, 'Recipe_ParmesanCrusted_Chicken_with_Mashed_Sweet_Potatoes_Roasted_Broccoli'),
(16, 'Pimento Cheeseburgers', 'with Sweet Potato Oven Fries', 'Tonight, the classic cheeseburger gets an easy, Southern-style lift from pimento cheese\r\n—a zesty spread made with cheddar, mayo, pickled peppers, and spices. Weʼre serving\r\nour burgers with sweet potato oven fries for a flavorful, seasonal twist on the usual side.', '1120_2PRE08_Pimento-Burgers_93077_WEB_Right_hi_res', '1120_ING_2PRE08_large_feature', 2, 3, 1, 'Recipe_Pimento_Cheeseburgers_with_Sweet_Potato_Oven_Fries'),
(17, 'Pork Chorizo Tacos', 'with Cheesy Roasted Potatoes', 'These tacos get plenty of bold flavor from ground chorizo (a type of spiced pork\r\nsausage), cooked into a delightfully saucy filling with cabbage and fresh citrus juices.\r\nOn the side, weʼre livening up roasted potatoes with garlic and Cotija cheese.', '0101_2PRE08_Saucy-Chorizo_Tacos_97328_WEB_SQ_hi_res', '0101_ING_2PRE08_large_feature', 3, 2, 2, 'Recipe_Pork_Chorizo_Tacos_with_Cheesy_Roasted_Potatoes'),
(18, 'Roasted Broccoli & Fregola Sarda Salad', 'with Hard-Boiled Eggs & Tahini Dressing', 'This Middle Eastern-inspired recipe is brimming with varied flavors and textures. Toasty\r\npearls of pasta, roasted vegetables (seasoned with savory, herby zaʼatar), crumbled\r\ncheese, and chopped almonds all come together in a smooth, nutty dressing.', '1218_2PV3_Brocoli-Fregola-Sarde_96640_SQ_hi_res', 'ING_12-18_2PV3_large_feature', 2, 1, 2, 'Recipe_Roasted_Broccoli_Fregola_Sarda_Salad_with_HardBoiled_Eggs_Tahini_Dressing'),
(19, 'Roasted Brussels Sprout & Freekeh Salad', 'with Lemon Yogurt & Barrel-Aged Feta', 'This Mediterranean-inspired grain salad is brimming with varied, vibrant flavors. Nutty freekeh and roasted Brussels sprouts get pops of sweetness from pickled peppers and dates, balanced by briny crumbled Feta. To dollop on top, weʼre serving lemon- seasoned yogurt for extra brightness.', '1225_2PV3_Broccoli-Freekeh_100110_SQ_hi_res', 'ING_12-25_2PV3_large_feature', 1, 1, 1, 'Recipe_Roasted_Brussels_Sprout_Freekeh_Salad_with_Lemon_Yogurt_Barrel-Aged_Feta'),
(20, 'Roasted Cauliflower Salad', 'with Caper Brown Butter & Parmesan Breadcrumbs', 'Seasonal salads donʼt get much more satisfying than this. Weʼre bringing roasted cauliflower and sautéed kale together with cheesy toasted breadcrumbs and a briny caper-studded dressing. Served on top, soft-boiled eggs add extra richness.', '0101_2PV3_Roasted_Cauliflower-Kale-Salad_97243_SQ_hi_res', 'ING_1-1_2PV3_large_feature', 1, 1, 2, 'Recipe_Roasted_Cauliflower_Salad_with_Caper_Brown_Butter_Parmesan_Breadcrumbs'),
(21, 'Roasted Chicken Fall Vegtables ', 'with Cranberry Ginger Compote', 'For this comforting autumn dinner, weʼre seasoning half chickens with the classic flavors of garlic, onion, and smoked paprika, then roasting them along with sweet potatoes and Brussels sprouts. The rich chicken finds delicious contrast in a tart-sweet compote, made simply by cooking fresh cranberries and ginger with a bit of sugar and water.', '1120_FPP_Roasted-Chicken_92314_WEB_SQ_hi_res', '1120_ING_FPP_large_feature', 1, 2, 2, 'Recipe_Roasted_Chicken_Fall_Vegetables_with_Cranberry_Ginger_Compote'),
(22, 'Roasted Pork Broccoli', 'with Apple, Cheese Sauce, Garlic Breadcrumbs', 'To elevate the classic savory-sweet pairing, weʼre topping roasted pork with sautéed apple in this crowd-pleasing recipe. The pork and a side of broccoli, roasted on the same sheet pan, come together with a rich, warming fontina cheese sauce.', '0108_2PRE08_Roasted-Pork_98452_WEB_SQ_hi_res', '0108_ING_2PRE08_large_feature', 1, 1, 1, 'Recipe_Roasted_Pork_Broccoli_with_Apple_Cheese_Sauce_Garlic_Breadcrumbs'),
(23, 'Roasted Red Pepper Pasta', 'with Lemon Parmesan Broccoli', 'In this quick-cooking recipe, whole grain pipe rigate gets pops of flavor from sweet roasted piquillo peppers and briny capers—plus a layer of exciting crunch from almonds. It all comes together in a creamy, mildly spicy sauce.\n', '0108_2PV1_Roasted-Pepper-Pasta_97907_SQ_hi_res', 'ING_1-8_2PV1_large_feature', 3, 1, 2, 'Recipe_Roasted_Red_Pepper_Pasta_with_LemonParmesan_Broccoli'),
(24, 'Roasted Squash Curry', 'with Crispy Mung Beans and Jasmine Rice', 'In this recipe, veggie curry gets a unique lift from spaghetti squash—oven-roasted, then broken into pasta-like strands with a fork. Weʼre finishing our squash and bok choy in a sauce made with fresh aromatics and two well-balanced pantry ingredients: spicy yellow curry paste and cooling coconut milk. A garnish of dried mung beans brings it all together with exciting crunch.\n', '1127_2PV3_Vegetable-Curry_74908_WEB_SQ_hi_res', 'ING_11-27_2PV3_large_feature.png', 2, 3, 3, 'Recipe_Roasted_Squash_Curry_with_Crispy_Mung_Beans_Jasmine_Rice'),
(25, 'Roasted Turkey Breast Farro Endive Salad', 'with Brown Butter Apple Compote', 'Fall comfort food gets a delicious lift in this recipe. A sweet, toasty compote (simply apple and shallot cooked in brown butter) balances our savory roasted turkey breast. On the side, weʼre tossing warm grains with endive—first cooked with a bit of honey and lemon to brighten its mildly bitter flavor.', '1211_2PRE08_Turkey_98057_WEB_SQ_hi_res', '1211_ING_2PRE08_large_feature', 1, 1, 1, 'Recipe_Roasted_Turkey_Breast_FarroEndive_Salad_with_Brown_Butter_Apple_Compote'),
(26, 'Salmon Honey Glazed Carrots', 'with Lemon Saffron Yogurt Sauce', 'This elegant dish gets unique flavor from a prized spice, saffron, used two ways: added to the water used to boil the potatoes and stirred into a creamy yogurt sauce. The bright sauce is delicious spooned over rich salmon, potatoes, and carrots—which get another flavor-packed lift from a glaze of honey and fragrant cumin. Aleppo pepper adds just a hint of spice throughout the dish, balanced by cooling fresh mint.', '1106_2PF_Salmon-Honey-Carrots_94837_SQ_hi_res', 'ING_11-06_2PF_large_feature', 1, 1, 1, 'Recipe_Salmon_HoneyGlazed_Carrots_with_LemonSaffron_Yogurt_Sauce'),
(27, 'Seared Chicken Mashed Potatoes', 'with Maple Glazed Carrots', 'Weʼre giving seared chicken a lift with a rich pan sauce, made with sweet maple syrup and tangy sherry vinegar. Itʼs the perfect accompaniment for creamy mashed potatoes and roasted carrots, dressed with a bit more maple syrup.', '0108_2PP_Chicken-Mashed-Potatoes_98562_SQ_hi_res', 'ING_1-8_2PP_large_feature', 1, 2, 2, 'Recipe_Seared_Chicken_Mashed_Potatoes_with_MapleGlazed_Carrots'),
(28, 'Seared Steaks Garlic Butter', 'with Oven Fries', '“Steak frites,” or steak with french fries, is classic French bistro fare. Tonightʼs steaks get another layer of rich flavor from garlic butter, spooned over them as they cook. Creamy mustard sauce is a perfect match for the rich steaks and hearty oven-roasted fries, while a simple salad adds refreshing contrast. (You may receive crisp romaine or tender butter lettuce.)', '1127_FPM_Steak-Fries_94016_WEB_SQ_hi_res', '1127_ING_FPM_large_feature', 1, 2, 2, 'Recipe_Seared_Steaks_Garlic_Butter_with_Oven_Fries'),
(29, 'Shiitake Hoisin Beef Burgers', 'with Miso Mayonnaise and Roasted Sweet Potatoes', 'These Asian-inspired burgers get their irresistible umami flavor from chopped shiitake mushrooms (mixed right into the beef) and a miso-mayo spread. Piled on top, crisp ribbons of bok choy round out the burgers, served with a side of roasted sweet potato wedges.', '1204_FPM_Shiitake-Hoisin-Burger_94634_WEB_SQ_hi_res.jpg', 'ING_1-1_2PF_large_feature', 2, 2, 3, 'Recipe_Shiitake_Hoisin_Beef_Burgers_with_Miso_Mayonnaise_Roasted_Sweet_Potatoes'),
(30, 'Shrimp Fra Diavolo', 'with Lumaca Rigata Pasta', 'Tonightʼs variation on the beloved Italian-American dish gets its “devilish” heat from Calabrian chile paste, mixed into a tangy-sweet tomato sauce. It perfectly coats shrimp, cabbage, and lumaca rigata pasta. A garnish of sliced almonds finishes the dish with contrasting crunch.', '0101_2PF_Shrimp-Fra-Diavolo_97454_SQ_hi_res', '', 3, 3, 2, 'Recipe_Shrimp_Fra_Diavolo_with_Lumaca_Rigata_Pasta'),
(31, 'Smoked Gouda & Mushroom Flatbread', 'with Endive & Apple Salad', 'For this rustic seasonal meal, weʼre topping flatbread—made by rolling out pizza dough until extra-thin—with two kinds of cheeses, including nutty smoked Gouda. Cremini mushrooms add even more irresistibly savory flavor to the flatbread, balanced by a bright, crisp endive and apple salad.\n', '0101_2PV2_Smoky-Kale-Flatbread_97386_SQ_hi_res.jpg', '0101_2PV2_Smoky-Kale-Mushroom-Flatberad_3151_WEB_high_feature.jpg', 1, 2, 2, 'Recipe_Smoked_Gouda_Mushroom_Flatbread_with_Endive_Apple_Salad'),
(32, 'Spicy Chicken Quesadillas', 'with Beet & Orange Salad', 'A seasonal salad of striped Chioggia beet, juicy orange, and peanuts is a fresh pairing for these zesty quesadillas. Weʼre seasoning the chicken filling with both jalapeño pepper and Mexican spices—balanced by a layer of melty white cheddar. Mexican crema brightened up with lime juice is perfect for dipping.', '1127_2PP_Spicy-Chicken-Quesadillas_93434_WEB_high_feature.jpg', 'ING_11-27_2PP_large_feature.png', 3, 2, 2, 'Recipe_Spicy_Chicken_Quesadillas_with_Beet_Orange_Salad'),
(33, 'Spicy Pork Korean Rice Cakes', 'with Bok Choy', 'In this crowd-pleasing recipe, a savory and spicy sauce (balanced by a touch of cooling crème fraîche) brings together ground pork, bok choy, and aromatics. Weʼre mixing in delightfully chewy tteok, or rice cakes—a staple of Korean cuisine.', '1225_FPM_Rice-Cakes_100092_WEB_SQ_hi_res.jpg', '1225_ING_FPM_large_feature.png', 3, 2, 1, 'Recipe_Spicy_Pork_Korean_Rice_Cakes_with_Bok_Choy'),
(34, 'Sweet Sour Vegetable StirFry', 'with Fried Eggs & Peanuts', 'Two kinds of citrus—seasonal orange and lemon—give the sauce for our stir-fried vegetables its irresistible sweet-sour balance. The carrots, celery, and bok choy perfectly contrast a rich fried egg and fluffy, radish-studded white rice.', '0108_2PV2_Stir-Fry-Egg_0195_SQ_hi_res.jpg', 'ING_1-8_2PV2_large_feature.png', 1, 1, 3, 'Recipe_Sweet_Sour_Vegetable_StirFry_with_Fried_Eggs_Peanuts'),
(35, 'Thai Curry Chicken', 'with Carrots & Bok Choy', 'In tonightʼs dish, the spicy and aromatic flavors of yellow curry paste—a Thai staple— shine through a lightly sweet coconut milk broth. Sautéed chicken, carrots, and bok choy give the curry plenty of hearty texture, while fluffy rice eagerly soaks up all the complex flavors. (Chefs, this curry paste packs a punch of heat, so be sure to use only as much as youʼd like!)', '1218_2PRE07_Thai-Curry-Chicken_96739_WEB_SQ_hi_res.jpg', '1218_ING_2PRE07_large_feature.png', 3, 2, 2, 'Recipe_Thai_Curry_Chicken_with_Carrots_Bok_Choy'),
(36, 'Tilapia & Black Lentil Salad', 'with Lemon Pan Sauce', 'In this dish, weʼre putting a twist on Italian gremolata: adding pickled peppers to the classic parsley, garlic, and lemon condiment. The bright, tangy flavors perk up a hearty salad of black lentils and roasted broccoli. Weʼre also using lemon juice as the base for an easy pan sauce to serve over our seared tilapia.', '1225_2PF_Tilapia_74912_SQ_hi_res.jpg', '1225_ING_2PF_large_feature.png', 2, 3, 2, 'Recipe_Tilapia_Black_Lentil_Salad_with_Lemon_Pan_Sauce'),
(37, 'Togarashi Chicken Lettuce Cups', 'with Orange & Radishes', 'These chicken lettuce cups get their dynamic flavor from togarashi seasoning— a staple of Japanese cuisine. Juicy bites of orange and crunchy radish add more bright flavor and color.', '0108_2PRE07_Lettuce-Cups_AR_0264_WEB_SQ_hi_res.jpg', '0108_ING_2PRE07_large_feature.png', 1, 1, 1, 'Recipe_Togarashi_Chicken_Lettuce_Cups_with_Orange_Radishes'),
(38, 'Top Chef Ginger-Marinated Grassfed Steaks', 'with Stir-Fried Vegetables & Jasmine Rice', 'In this recipe—inspired by our Quickfire Challenge from Top Chef Season 15 on Bravo—we’re marinating grassfed steaks in fresh ginger, soy sauce, and\n citrusy ponzu sauce. The extra marinade transforms into an easy pan sauce, which adds punchy flavor to the steaks and a side of jasmine rice.', '0108_2PM_Ginger-Steak-Stirfry_98208_201_SQ_hi_res.jpg', 'ING_1-8_2PM_large_feature.png', 3, 2, 3, 'Recipe_Top_Chef_Ginger-Marinated_Grassfed_Steaks_with_Stir-Fried_Vegetables_Jasmine_Rice'),
(39, 'Top Chef Seared Grassfed Steaks', 'with Sweet Chili Glazed Vegetables', 'In this recipe, inspired by our Quickfire Challenge from Top Chef Season 15 on Bravo, simple grassfed steaks and rice get a sweet, tart, and spicy lift from glazed mushrooms and bok choy. Sliced radishes, softened a bit with lime juice, finish the dish off with subtle crunch.', '0108_FPM_Seared-Steaks_97965_WEB_SQ_hi_res.jpg', '0108_ING_FPM_large_feature.png', 2, 3, 2, 'Recipe_Top_Chef_Seared_Grassfed_Steaks_with_Sweet_Chili-Glazed_Vegetables'),
(40, 'Tuscan Chicken & Green Lentil Stew', 'with Goat Cheese', 'In this comforting cold-weather recipe, weʼre serving Tuscan-spiced chicken over tender green lentils and vegetables cooked in a light, savory tomato broth. Capers and crushed red pepper add briny flavor and a touch of heat to cut through the rich, earthy stew. (Chefs, rinsing the lentils after cooking removes excess starch, resulting in a more delicate flavor.', '0101_2PP_Chicken-Lentil-Stew_100567_SQ_hi_res.jpg', 'ING_1-1_2PP_large_feature.png', 1, 2, 1, 'Recipe_Tuscan_Chicken_Green_Lentil_Stew_with_Goat_Cheese');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
